import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
}

test("agent-kit copilot instructions keep rationale-first memory guardrails", () => {
  const content = read(".github/agent-kit/templates/copilot-instructions.md");

  assert.match(content, /Memory Quality Guardrails/);
  assert.match(content, /reasoning behind the action/i);
  assert.match(content, /No execution-only memory exemption/i);
  assert.match(content, /Repo notes are not a substitute/i);
  assert.match(content, /Create or update an MCP-backed plan memory/i);
  assert.match(content, /Sub-agent coordination/i);
});

test("agent-kit neurodivergent agent rejects execution-only memory logs", () => {
  const content = read(".github/agent-kit/templates/neurodivergent-agent.agent.md");

  assert.match(content, /No Execution-Only/i);
  assert.match(content, /durable principle/i);
  assert.match(content, /reasoning behind them/i);
});

test("workflow instruction and issue prompt require explicit why capture", () => {
  const workflow = read(".github/agent-kit/templates/nd-memory-workflow.instructions.md");
  const prompt = read(".github/agent-kit/templates/memory-driven-issue-execution.prompt.md");

  assert.match(workflow, /Store the why behind decisions/i);
  assert.match(workflow, /Record progress, validation, and hand-off writes on the active task thread/i);
  assert.match(workflow, /Require `connect_memories` whenever you create a new plan or task-thread node/i);
  assert.match(workflow, /continue locally and do not treat their absence as a blocker/i);
  assert.match(workflow, /durable principle/i);
  assert.match(prompt, /durable principle behind the work/i);
  assert.match(prompt, /Do not leave execution-only logs/i);
  assert.match(prompt, /Prefer `update_memory` when continuing an active slice/i);
  assert.match(prompt, /Do not treat repo-local notes, scratch docs, or TODO files as substitutes/i);
  assert.match(prompt, /If sub-agents are available and the work is bounded/i);
});

// prepare-agent-kit.cjs copies .github/agent-kit/ -> templates/agent-kit/, and it
// does so by rmSync'ing the destination first. So .github/ is the SOURCE you edit
// and templates/agent-kit/ is GENERATED OUTPUT: anything hand-written there is
// destroyed at the next prepack, silently and long after the change was reviewed.
// It has happened twice — a Claude-brand install section, and an accepted review
// suggestion, both applied to the generated copy because that is the file that
// shows up in a diff.
const AUTHORED_DIR = path.join(repoRoot, ".github", "agent-kit", "templates");
const GENERATED_DIR = path.join(repoRoot, "templates", "agent-kit");
const EDIT_HINT = "Edit .github/agent-kit/ instead — templates/agent-kit/ is regenerated by scripts/prepare-agent-kit.cjs and your change will be destroyed.";

test("the generated agent-kit README matches its source", () => {
  // The gap that let a whole documentation section die: the alignment test below
  // skips README.md because it comes from a DIFFERENT source path, and nothing
  // else checked it. A hand-edit here used to pass every test in the repo.
  const authored = fs.readFileSync(path.join(repoRoot, ".github", "agent-kit", "README.md"), "utf8");
  const generated = fs.readFileSync(path.join(GENERATED_DIR, "README.md"), "utf8");
  assert.equal(generated, authored,
    `templates/agent-kit/README.md drifted from .github/agent-kit/README.md. ${EDIT_HINT}`);
});

test("source templates stay aligned with packaged agent-kit copies", () => {
  // NOTE: these were named backwards. templates/agent-kit/ is the OUTPUT.
  const sourceDir = GENERATED_DIR;
  const packagedDir = AUTHORED_DIR;

  // README.md comes from .github/agent-kit/README.md rather than templates/, so
  // it is covered by its own test above rather than skipped outright.
  const EXCLUDED = new Set(["README.md"]);

  const sourceFiles = new Set(fs.readdirSync(sourceDir).filter((f) => !EXCLUDED.has(f)));
  const packagedFiles = new Set(fs.readdirSync(packagedDir).filter((f) => !EXCLUDED.has(f)));

  for (const name of packagedFiles) {
    assert.ok(sourceFiles.has(name), `${name} is generated output with no authored source. ${EDIT_HINT}`);
  }
  for (const name of sourceFiles) {
    assert.ok(packagedFiles.has(name), `${name} is authored but was never generated — run \`node scripts/prepare-agent-kit.cjs\`.`);
  }

  for (const name of packagedFiles) {
    const source = fs.readFileSync(path.join(sourceDir, name), "utf8");
    const packaged = fs.readFileSync(path.join(packagedDir, name), "utf8");
    assert.equal(source, packaged, `${name} drifted between authored and generated copies. ${EDIT_HINT}`);
  }
});